// Generated by CoffeeScript 1.3.3

$.fn.serializeObject = function() {
  var a, o;
  o = {};
  a = this.serializeArray();
  $.each(a, function() {
    if (o[this.name]) {
      if (!o[this.name].push) {
        o[this.name] = [o[this.name]];
      }
      return o[this.name].push(this.value || "");
    } else {
      return o[this.name] = this.value || "";
    }
  });
  return o;
};

$(function() {
  $(document).on('submit', 'form', function(e) {
    return e.preventDefault();
  });
  $(document).on('click', '.subnav .disabled', function(e) {
    return e.preventDefault();
  });
  $(document).on('click', '[data-nav="main"] a', function(e, onload) {
    var $a, $activePage, $loadPage, $wrap, page;
    if (onload == null) {
      onload = false;
    }
    $a = $(this);
    $wrap = $a.parents('[data-nav="main"]:eq(0)');
    page = $a.attr('data-load-page');
    $activePage = $('[data-page]:visible');
    $loadPage = $('[data-page="' + page + '"]');
    $wrap.find('.active').removeClass('active');
    $a.parents('li:eq(0)').addClass('active');
    if (onload) {
      return $loadPage.show();
    } else {
      if ($activePage.length && $activePage.data('page') !== $loadPage.data('page')) {
        return $activePage.fadeOut('fast', function() {
          return $loadPage.fadeIn('fast');
        });
      } else {
        return $loadPage.fadeIn('fast');
      }
    }
  });
  return (function() {
    var loadPage, page;
    loadPage = function(page) {
      if (page == null) {
        page = 'home';
      }
      return $('[data-nav="main"] [data-load-page="' + page + '"]').trigger('click', [true]);
    };
    page = location.hash.search('member') !== -1 ? 'members' : 'home';
    return loadPage(page);
  })();
});
