// Generated by CoffeeScript 1.3.3
/*
COLLECTIONS
*/

App.Collection.Members = Backbone.Collection.extend({
  initialize: function(models, options) {
    return this.filter = options.filter;
  },
  model: App.Model.Member,
  url: function() {
    var q;
    q = this.filter ? '?filter=' + this.filter : '';
    return App.api + 'members' + q;
  }
});
