// Generated by CoffeeScript 1.3.3
/*
MODELS
*/

App.Model.Member = Backbone.Model.extend({
  defaults: {
    city: 'na',
    state: 'na',
    country: 'na',
    type: 'patient'
  },
  url: function() {
    var base;
    base = "" + App.api + "members/";
    if (this.isNew()) {
      return base;
    } else {
      return base + this.id;
    }
  },
  validate: {
    username: {
      required: true
    },
    name: {
      required: true
    }
  }
});
