// Generated by CoffeeScript 1.3.3
var App;

App = {};

App.api = 'http://localhost:3000/';

App.Collection = {};

App.Model = {};

App.Routes = {};

App.Router = {};

App.View = {};

App.View.Member = {};
