// Generated by CoffeeScript 1.3.3
/*
# HOME PAGE
*/

App.View.Home = Backbone.View.extend({
  tagName: 'div',
  className: 'home',
  initialize: function() {
    return $('[data-template="home"] > div').html(this.render().el);
  },
  render: function(eventName) {
    var template;
    template = Handlebars.templates['home'];
    this.$el.html(template());
    return this;
  }
});
