// Generated by CoffeeScript 1.3.3
(function() {
  var app, autoId, express, members;

  express = require("express");

  app = express.createServer();

  autoId = 1;

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.all("/*", function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Content-Type, X-Requested-With");
    res.header("Access-Control-Allow-Methods", "POST, GET, PUT, DELETE, OPTIONS");
    return next();
  });

  app.get("/", function(req, res) {
    return res.send("Yo, I'm the super ill server!");
  });

  app.get("/members", function(req, res) {
    var fMembers, filter;
    filter = req.query["filter"];
    fMembers = members;
    if (filter) {
      fMembers = members.filter(function(element) {
        return element.type === filter.substring(0, filter.length - 1);
      });
    }
    return res.json(fMembers);
  });

  app.post("/members", function(req, res) {
    var id;
    console.log("POST");
    id = members.length;
    req.body.id = autoId++;
    members.push(req.body);
    return res.json(members[id]);
  });

  app.get("/members/:id", function(req, res) {
    var id;
    id = parseInt(req.params.id);
    members.filter(function(element) {
      if (element.id === id) {
        return id = members.indexOf(element);
      }
    });
    return res.json(members[id]);
  });

  app.del("/members/:id", function(req, res) {
    var id, member;
    console.log("DELETE");
    id = parseInt(req.params.id);
    members.filter(function(element) {
      if (element.id === id) {
        return id = members.indexOf(element);
      }
    });
    member = members[id];
    members.splice(id, 1);
    return res.json(member);
  });

  app.put("/members/:id", function(req, res) {
    var id;
    console.log("PUT");
    id = parseInt(req.params.id);
    members.filter(function(element) {
      if (element.id === id) {
        return id = members.indexOf(element);
      }
    });
    members[id] = req.body;
    return res.json(members[id]);
  });

  members = [
    {
      id: autoId++,
      username: "jyounce",
      name: "Judd Younce",
      city: "Ashland",
      state: "Kentucky",
      country: "United States",
      type: "patient"
    }, {
      id: autoId++,
      username: "superman",
      name: "Clark Kent",
      city: "Metropolis",
      state: "Krypton",
      country: "DC Universe",
      type: "patient"
    }, {
      id: autoId++,
      username: "batman",
      name: "Bruce Wayne",
      city: "Gotham City",
      state: "Illinois",
      country: "United States",
      type: "patient"
    }, {
      id: autoId++,
      username: "iron-man",
      name: "Edward Stark",
      city: "New York",
      state: "New York",
      country: "United States",
      type: "patient"
    }, {
      id: autoId++,
      username: "captain-america",
      name: "Steve Rogers",
      city: "New York",
      state: "New York",
      country: "United States",
      type: "patient"
    }, {
      id: autoId++,
      username: "gclooney",
      name: "George Clooney",
      city: "Lexington",
      state: "Kentucky",
      country: "United States",
      type: "doctor"
    }, {
      id: autoId++,
      username: "thanks",
      name: "Tom Hanks",
      city: "Concord",
      state: "California",
      country: "United States",
      type: "doctor"
    }, {
      id: autoId++,
      username: "wferrell",
      name: "Will Ferrell",
      city: "Irvine",
      state: "California",
      country: "United States",
      type: "doctor"
    }, {
      id: autoId++,
      username: "gpaltrow",
      name: "Gwyneth Paltrow",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      type: "nurse"
    }, {
      id: autoId++,
      username: "kwinslet",
      name: "Kate Winslet",
      city: "England",
      state: "na",
      country: "United Kingdom",
      type: "nurse"
    }, {
      id: autoId++,
      username: "cdiaz",
      name: "Cameron Diaz",
      city: "San Diego",
      state: "California",
      country: "United States",
      type: "nurse"
    }
  ];

  app.listen(3000);

  console.log("Listening on port 3000! Sweet!");

}).call(this);
