// Generated by CoffeeScript 1.3.3
var QueryString;

QueryString = (function() {

  function QueryString(qString) {
    this.qString = qString != null ? qString : null;
    this.qString = this.qString ? this.qString : window.location.hash.substring(1);
    this.qString = this.qString.split("?")[1] ? this.qString.split("?")[1] : '';
  }

  QueryString.prototype.getVal = function(key, def) {
    var i, pair, vars;
    if (def == null) {
      def = '';
    }
    vars = this.qString.split("&");
    i = 0;
    while (i < vars.length) {
      pair = vars[i].split("=");
      if (pair[0] === key) {
        return unescape(pair[1]);
      }
      i++;
    }
    return def;
  };

  return QueryString;

})();
